services:
  # A web service
  - type: web
    name: parate-welding-workshop
    env: python
    plan: free
    buildCommand: pip install -r railway_requirements.txt
    startCommand: gunicorn main:app
    disk:
      name: pdf-storage
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: FLASK_ENV
        value: production
      - key: RAILWAY_ENVIRONMENT
        value: "1"
      - key: PDF_STORAGE_PATH
        value: /var/data/generated_pdfs
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: parate-db
          property: connectionString
    
  # A PostgreSQL database
databases:
  - name: parate-db
    plan: free
    databaseName: parate_db
    user: parate_user